using System;
using NeonGrid.Simulation;

namespace NeonGrid.Session
{
    /// <summary>
    /// Captures only the logical tile state used to reconstruct a board. Transient
    /// electrical values are deliberately regenerated by CircuitSimulation.
    /// </summary>
    internal sealed class BoardPersistentSnapshot
    {
        private readonly BoardState board;

        private BoardPersistentSnapshot(BoardState board)
        {
            this.board = board;
        }

        public static BoardPersistentSnapshot Capture(BoardState source)
        {
            if (source == null) throw new ArgumentNullException(nameof(source));
            return new BoardPersistentSnapshot(source.CreateIndependentCopy());
        }

        public BoardState Restore()
        {
            return board.CreateIndependentCopy();
        }
    }
}
